=== campagna91/Quartier6su7/public_html/xml/ideeAccept.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://localhost" targetNamespace="http://localhost" elementFormDefault="qualified">
            
            <xsd:element name="idee" type="Tidee"/>
            
            <xsd:complexType name="Tidee">
                  <xsd:sequence>
                    <xsd:element name="idea" type="Tidea" maxOccurs="unbounded"/>
                  </xsd:sequence>
            </xsd:complexType>
            
            <xsd:complexType name="Tidea">
                <xsd:sequence>
                    <xsd:element name="nome" type="xsd:string"/>
                    <xsd:element name="email" type="xsd:string"/>
                    <xsd:element name="telefono" type="xsd:decimal"/>
                    <xsd:element name="titolo" type="xsd:string"/>
                    <xsd:element name="testo" type="xsd:string"/>
                </xsd:sequence>
                <xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required"/>
            </xsd:complexType>         
</xsd:schema>

=== campagna91/Quartier6su7/public_html/xml/ideeAccept.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<idee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://localhost ideeAccept.xsd">
<idea id="1"><nome>simone</nome><email>simone@gmail.com</email><titolo>fjdklasjfklj</titolo><telefono>3402290812</telefono><testo>dkfkasklflòkDescrizione idea</testo></idea><idea id="2"><nome>Paola</nome><email>paola89@libero.it</email><titolo>Finta mela marcia caramellata</titolo><telefono>3462136029</telefono><testo>Ciao a tutti sono paola. Sono in possesso di uno stand di mele caramellate in un paio di parchi giochi dispersi per la nazione  Vorrei sapere se l'idea come da titolo detta vi pare una buona idea. &#13;
Sappiatemi dire qualcosa &#13;
Paola</testo></idea><idea id="3"><nome>Marco</nome><email>marchett8@yahoo.it</email><titolo>Finto cieco</titolo><telefono>3289090012</telefono><testo>Salve a tutti &#13;
Lo so che forse potrebbe sembrare vecchia come idea, ma io vorrei impersonare un vecchiotto cieco finito dentro ad un negozio di abbigliamento qui della mia città . &#13;
Sono già daccordo con un negozio della mia città che sarebbe disposto a farmi entrare nei camerini senza denunciarmi. Che dite ? &#13;
&#13;
Marco</testo></idea><idea id="4"><nome>simoncino</nome><email>simone@gmail.com</email><titolo>my idea</titolo><telefono>343434343</telefono><testo>dkjflskjfkfjldsfaòlkjDescrizione idea</testo></idea><idea id="5"><nome>ciap</nome><email>ciao@gmail.com</email><titolo>mio titolo</titolo><telefono>3402290812</telefono><testo>La mia descrizione </testo></idea></idee>
